name: Build & Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

# Variables could be hard coded here
env:
  JAVA_VERSION: 21
#  APPNAME: MyAppName
#  VERSION: 0.0.1

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract build info from maven pom.xml
        run: |
          [xml]$pom = Get-Content pom.xml
          $appName = $pom.project.artifactId
          $version = $pom.project.version
          $javaVersion = $pom.project.properties."java-version"
          echo "APPNAME=$appName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "JAVA_VERSION=$javaVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Jar
        run: |
          mvn clean compile assembly:single


      #      - name: Extract app version from pom.xml (ubuntu)
      #        run: |
      #          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      #          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      #      - name: Install jpackage (for Linux)
      #        run: sudo apt-get install -y fakeroot

      - name: Build Windows Portable
        run: |
          jpackage `
            --name ${{ env.APPNAME }} `
            --type app-image `
            --input target/jar `
            --main-jar ${{ env.APPNAME }}.jar `
            --main-class io.github.zmilla93.MainKt `
            --dest win-portable `
            --arguments '--distribution:win-portable'
          Compress-Archive -Path win-portable/* -Destination ${{ env.APPNAME }}-win-portable.zip

      # FIXME : Build to dest?
      - name: Build Windows Installer (MSI)
        run: |
          jpackage `
            --name ${{ env.APPNAME }} `
            --type msi `
            --input target/jar `
            --main-jar ${{ env.APPNAME }}.jar `
            --main-class io.github.zmilla93.MainKt `
            --app-version ${{ env.VERSION }} `
            --dest win-msi `
            --arguments '--distribution:win-msi' `
            --win-per-user-install `
            --win-console `
            --win-shortcut-prompt `
            --win-shortcut `
            --win-menu
          move win-msi/${{ env.APPNAME }}-${{ env.VERSION }}.msi ${{ env.APPNAME }}-win-installer.msi
      
      

      #      #      FIXME: Combine with previous step?
      #      - name: Zip the Windows Portable
      #        #        shell: powershell
      #        run: Compress-Archive -Path win-portable/* -Destination JUpdate-win-portable.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.APPNAME }} ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          artifacts: target/jar/${{ env.APPNAME }}.jar, ${{ env.APPNAME }}-win-portable.zip, ${{ env.APPNAME }}-win-installer.msi
          token: ${{ secrets.GITHUB_TOKEN }}

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download built ZIP file
#        uses: actions/download-artifact@v4
#        with:
#          name: app-image
#
#      - name: Create GitHub release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: MyApp.zip
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag_name: ${{ github.ref_name }}
