name: Build & Release

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_NAME: UpdateApp

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust Java version as needed

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

#FIXME : This this copy required?
      - name: Build with Maven
        run: |
          mvn clean compile assembly:single
          copy target/jar/JUpdater.jar JUpdater.jar

      - name: Get App Version
        id: get_version
        shell: powershell
        run: |
          [xml]$pom = Get-Content pom.xml
          $version = $pom.project.version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

#      - name: Extract app version from pom.xml (ubuntu)
#        run: |
#          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
#          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      #      - name: Install jpackage (for Linux)
      #        run: sudo apt-get install -y fakeroot

#      - name: Create app-image using jpackage
#        shell: bash
#        run: |
#          mkdir -p dist
#          jpackage \
#            --input target/jar \
#            --name JUpdater \
#            --main-jar JUpdater.jar \
#            --main-class io.github.zmilla93.MainKt \
#            --type app-image \
#            --dest dist

#      - name: Zip the app-image
#        run: Compress-Archive -Path dist/* -Destination JUpdater-win-portable.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.PROJECT_NAME }} ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          artifacts: JUpdater.jar, JUpdater-win-portable.zip
          token: ${{ secrets.GITHUB_TOKEN }}

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download built ZIP file
#        uses: actions/download-artifact@v4
#        with:
#          name: app-image
#
#      - name: Create GitHub release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: MyApp.zip
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag_name: ${{ github.ref_name }}
