name: Build & Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

#env:
#  PROJECT_NAME: UpdateApp

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Get App Version
        id: get_version
        run: |
          [xml]$pom = Get-Content pom.xml
          $appName = $pom.project.artifactId
          $version = $pom.project.version
          echo "APPNAME=$appName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo {$version}
          echo {$appName}
      #FIXME : This this copy required?
      - name: Build with Maven
        run: |
          mvn clean compile assembly:single
      #          copy target/jar/JUpdater.jar JUpdater.jar


      #      - name: Extract app version from pom.xml (ubuntu)
      #        run: |
      #          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      #          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      #      - name: Install jpackage (for Linux)
      #        run: sudo apt-get install -y fakeroot

      - name: Build Windows Installer
#        shell: bash
        run: |
          jpackage `
            --name JUpdate `
            --type msi `
            --input target/jar `
            --main-jar JUpdate.jar `
            --main-class io.github.zmilla93.MainKt `
            --app-version JUpdate `
            --dest win-msi `
            --win-per-user-install `
            --win-console `
            --win-shortcut-prompt `
            --win-shortcut `
            --win-menu
          copy win-msi/JUpdate-0.0.1.msi JUpdate-win-installer.msi

      - name: Build Windows Portable
        run: |
          jpackage `
            --name JUpdate `
            --type app-image `
            --input target/jar `
            --main-jar JUpdate.jar `
            --main-class io.github.zmilla93.MainKt `
            --dest win-portable
          Compress-Archive -Path win-portable/* -Destination JUpdater-win-portable.zip

      #      FIXME: Combine with previous step?
      - name: Zip the Windows Portable
        #        shell: powershell
        run: Compress-Archive -Path win-portable/* -Destination JUpdate-win-portable.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: JUpdate ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          artifacts: target/jar/JUpdate.jar, JUpdate-win-portable.zip, JUpdate-win-installer.msi
          token: ${{ secrets.GITHUB_TOKEN }}

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download built ZIP file
#        uses: actions/download-artifact@v4
#        with:
#          name: app-image
#
#      - name: Create GitHub release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: MyApp.zip
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag_name: ${{ github.ref_name }}
